product-name: cf
errand-config:
  deploy-autoscaler:
    post-deploy-state: false
  deploy-notifications:
    post-deploy-state: false
  deploy-notifications-ui:
    post-deploy-state: false
  metric_registrar_smoke_test:
    post-deploy-state: false
  nfsbrokerpush:
    post-deploy-state: false
  push-apps-manager:
    post-deploy-state: false
  push-usage-service:
    post-deploy-state: false
  rotate_cc_database_key:
    post-deploy-state: false
  smbbrokerpush:
    post-deploy-state: false
  smoke_tests:
    post-deploy-state: true
  test-autoscaling:
    post-deploy-state: false
resource-config:
  backup_restore:
    instances: 0
  ha_proxy:
    instances: 1
  mysql_monitor:
    instances: 0
product-properties:
  .cloud_controller.apps_domain:
    type: wildcard_domain
    value: nimbus-tas.cf-app.com
  .cloud_controller.system_domain:
    type: wildcard_domain
    value: nimbus-tas.cf-app.com
  .ha_proxy.skip_cert_verify:
    type: boolean
    value: true
  .ha_proxy.static_ips:
    type: ip_ranges
    value: 192.168.111.153
  .mysql_monitor.recipient_email:
    type: string
    value: bogus@this.is.just.a.placeholder.pivotal.io
  .properties.credhub_internal_provider_keys:
    value:
    - key:
        secret: pivotalcfpivotalcfpivotalc
      name: primary-encryption-key
      primary: true
  .properties.haproxy_forward_tls:
    value: disable
  .properties.secure_service_instance_credentials:
    type: boolean
    value: true
  .properties.security_acknowledgement:
    type: string
    value: I agree
